### PR TITLE
Added sigscanning

### PR DESCRIPTION
**Pull request by Jujstme**
Updated the script, now it uses sigscanning which makes it compatible with all past and future patches of the game (including 1.2.8 Win10)

### CODE REVIEW

**Comment by Adventium-underscore** [comment]
While I don't know enough about .asl or in-depth memory stuff to know how this exactly works, I do at least understand what it's doing. Really cool! Would probably save me a bunch of work.

However, this assumes that the pointer paths past the base address never change between updates, which isn't true. As is, this would only work for 1.3.1+. So far, the only difference between the paths is 0x948 -> 0x950 -> 0x958 -> 0x960 (current). If you figure out a way around that, that would be awesome, but don't sweat it if you don't.

Is the backward compatibility _really_ necessary? Not really but I do like having it there lol

I will do a bit of testing on my side and talk with my friend that would fully understand the memory code, then probably merge into the autosplitter. Thank you for this!

**Comment by Adventium-underscore** [comment]
Out of interest, how did you find the values you needed?

**Comment by Jujstme** [comment]
Sigscanning is a matter of looking into the .exe and find the value you need. Simple as that.
You can, however, keep the state descriptors for the old versions, solving the issue with that pointer.

**Comment by Adventium-underscore** [comment]
Fair enough, I guess. I'm mostly interested in what you did that led to the pattern used.

**Comment by electraminer** [comment]
(I think we've figured it out now, the sigscan is a part of assembly code that uses RIP relative addressing, hence the addr + 4 + [addr] calculation)

**Comment by Jujstme** [comment]
Yes, it's part of assembly code. You can inspect the exe with IDA, ghidra, or other disassemblers.

**Pull request merged**
